Updated CI/CD pipeline.

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,14 +1,18 @@
-image: ubuntu:24.04
-
 stages:
 - build
 
-# Notes:
-# - Variable GITLAB_REPO_ACCESS_TOKEN shall be defined
+default:
+  image: ubuntu:24.04
+  tags:
+    - docker
 
 before_script:
-    # Install build dependencies
-    - apt-get update && apt-get -y install make cmake g++ zlib1g-dev libxml2-dev libedit-dev libsdl1.2-dev libnode-dev gettext-base yq autoconf automake libtool pkg-config libpython3.12-dev python3-distutils-extra opam wget
+  # - Variable GITLAB_REPO_ACCESS_TOKEN shall be defined
+  # - Variable NPROC shall be defined
+  - if [ -z "${GITLAB_REPO_ACCESS_TOKEN}" ]; then echo "ERROR! GITLAB_REPO_ACCESS_TOKEN is unset"; exit 1; fi
+  - if [ -z "${NPROC}" ]; then echo "ERROR! NPROC is unset"; exit 1; fi
+  # Install build dependencies
+  - apt-get update && apt-get -y install make cmake g++ zlib1g-dev libxml2-dev libedit-dev libsdl1.2-dev libnode-dev gettext-base yq autoconf automake libtool pkg-config libpython3.12-dev python3-distutils-extra opam wget
 
 build_unisim:
   stage: build
@@ -33,13 +37,13 @@ build_unisim:
     mkdir objdir
     pushd objdir
     ../configure --prefix="$(realpath "$(pwd)/../install")"
-    make -j $(nproc)
+    make -j ${NPROC}
     make install
     popd
     mkdir objdir-posix
     pushd objdir-posix
     ../configure --prefix="$(realpath "$(pwd)/../install-posix")" --enable-pthreads
-    make -j $(nproc)
+    make -j ${NPROC}
     make install
     popd
     popd
@@ -57,7 +61,7 @@ build_unisim:
     pushd src/scml2_logging
     make scml2_logging.h
     popd
-    make -j $(nproc)
+    make -j ${NPROC}
     make install
     popd
     mkdir objdir-posix
@@ -70,7 +74,7 @@ build_unisim:
     pushd src/scml2_logging
     make scml2_logging.h
     popd
-    make -j $(nproc)
+    make -j ${NPROC}
     make install
     popd
     popd
@@ -82,7 +86,7 @@ build_unisim:
     mkdir build
     pushd build
     cmake -DCMAKE_INSTALL_PREFIX="$(realpath "$(pwd)/../install")" ..
-    cmake --build . --config Release --parallel $(nproc)
+    cmake --build . --config Release --parallel ${NPROC}
     cmake --build . --config Release --target install
     popd
     popd
@@ -94,7 +98,7 @@ build_unisim:
     mkdir build
     pushd build
     ../configure --prefix="$(realpath "$(pwd)/../install")" --enable-builtin-clz --enable-round-odd --enable-fast-int64 --enable-fast-div32to16 --enable-fast-div64to32 --with-inline-level=5
-    make -j $(nproc)
+    make -j ${NPROC}
     make install
     popd
     popd
@@ -156,6 +160,8 @@ build_unisim:
         enabled: true
         command: |
           dune build @install
+          dune install
+          dune clean
     EOF
       else
         for FLAVOR in debug release; do
@@ -189,10 +195,10 @@ build_unisim:
           fi
           case "${FLAVOR}" in
             debug)
-              OPTIONS+=" 'CXXFLAGS=-O0 -g -Wall -Wno-deprecated -fdiagnostics-color=always'"
+              OPTIONS+=" 'CXXFLAGS=-O0 -g -Wall -Wno-deprecated -Woverloaded-virtual=0 -fdiagnostics-color=always'"
               ;;
             release)
-              OPTIONS+=" 'CXXFLAGS=-O3 -Wall -Wno-deprecated -fdiagnostics-color=always'"
+              OPTIONS+=" 'CXXFLAGS=-O3 -Wall -Wno-deprecated -Woverloaded-virtual=0 -fdiagnostics-color=always'"
               ;;
           esac
           cat << EOF
@@ -205,8 +211,9 @@ build_unisim:
           INSTALL_DIR="\$(pwd)/../../install/${FLAVOR}" &&
           mkdir -p "\${INSTALL_DIR}" &&
           ../../source/configure --prefix="\${INSTALL_DIR}"${OPTIONS} &&
-          make -j \$(nproc) &&
-          make install
+          make -j \${NPROC} &&
+          make install &&
+          make clean
     EOF
         done
       fi
@@ -215,3 +222,6 @@ build_unisim:
     
     # build everything with unisimatic
     ./unisim_tools/unisimatic/unisimatic --config=config.yaml build '*'
+    
+    # clean everything with unisimatic
+    ./unisim_tools/unisimatic/unisimatic --config=config.yaml clean '*'
