[Unisimatic] Simplified verbosity level for commands (removed --silent-build options from previous commits).
[General]
Added libieee1666 in CI/CD pipeline.
Fixed compilation issues.

diff --git a/unisim_tools/unisimatic/unisimatic b/unisim_tools/unisimatic/unisimatic
--- a/unisim_tools/unisimatic/unisimatic
+++ b/unisim_tools/unisimatic/unisimatic
@@ -33,7 +33,6 @@ VERBOSE_LEVEL=${DEFAULT_VERBOSE_LEVEL}
 INCLUDE_UNTRACKED_FILES='no'
 COVERAGE='no'
 SYNTHESIZE='no'
-SILENT_BUILD='no'
 RUN_BUILD_COMMAND='yes'
 OPTIONS=()
 
@@ -127,10 +126,34 @@ function bad()
 
 ############################################# utility functions #####################################################
 
+# sort lines of a file
 function sort_file()
 {
 	local FILE="$1"
 	LC_ALL=C sort -u -o "${FILE}" "${FILE}"
+}
+
+# run a command in another shell process, and return the command exit status.
+# when verbose level < 4, only print all command outputs on standard error output when command has failed.
+function run_command()
+{
+	local COMMAND="$1"
+	local STATUS=0
+	local TMP_FILE
+	if [ ${VERBOSE_LEVEL} -lt 4 ]; then
+		TMP_FILE="$(mktemp)"
+		"${SHELL}" -e -c "${COMMAND}" &> "${TMP_FILE}"
+		STATUS=$?
+		if [ ${STATUS} -ne 0 ]; then
+			cat "${TMP_FILE}" >&2
+		fi
+		rm -f "${TMP_FILE}"
+	else
+		"${SHELL}" -e -c "${COMMAND}"
+		STATUS=$?
+	fi
+
+	return ${STATUS}
 }
 
 #################################################### help ###########################################################
@@ -296,11 +319,21 @@ Options:
   --synthesize
         Synthesize printing (to be used in conjunction with commands 'coverage' or 'orphans')
 
-  --silent-build
-        Silent build and print tail of build command output on error (see command 'build')
-
   --dont-run-build-command
         Don't run build command (see command 'build')
+
+Verbose levels:
+
+  +-------+---------------------+
+  | value |  description        |
+  +-------+---------------------+
+  |   0   | no output           |
+  |   1   | error messages      |
+  |   2   | warning messages    |
+  |   3   | general information |
+  |   4   | debug               |
+  |   5   | annoying debug      |
+  +-------+---------------------+
 
 License:
 
@@ -2280,7 +2313,7 @@ function output_configure_ac()
 	   has_to_build "${PACKAGE_CONFIGURE_AC}" "${SELF}"; then
 		package > /dev/null # die if missing
 		version > /dev/null # die if missing
-		info "Generating $(package)' configure.ac"
+		info "Generating \"$(package)\" configure.ac"
 		if [ $# -ne 0 ]; then
 cat << EOF  > "${PACKAGE_CONFIGURE_AC}"
 # This file is automatically generated by ${APP_NAME^}.
@@ -2311,7 +2344,7 @@ function output_makefile_am()
 	   has_to_build "${PACKAGE_MAKEFILE_AM}" "${SELF}"; then
 		package > /dev/null # die if missing
 		version > /dev/null # die if missing
-		info "Generating $(package) Makefile.am"
+		info "Generating \"$(package)\" Makefile.am"
 cat << EOF > "${PACKAGE_MAKEFILE_AM}"
 # This file is automatically generated by ${APP_NAME^}.
 # You should not modify this file.
@@ -2336,7 +2369,7 @@ function build_configure()
 	
 	if [ "${has_to_build_configure}" = "yes" ]; then
 		package > /dev/null # die if missing
-		info "Building $(package) configure"
+		info "Building \"$(package)\" configure"
 		local PACKAGE_CONFIGURE_AC="${DIST_DIR}/configure.ac"
 		[ -f "${PACKAGE_CONFIGURE_AC}" ] || die "Missing configure.ac. Did you forget to call output_configure_ac?"
 		local PACKAGE_MAKEFILE_AM="${DIST_DIR}/Makefile.am"
@@ -2352,11 +2385,9 @@ function build_configure()
 		fi
 		CMD+=" && automake -ac"
 		info "Running: ${CMD}"
-		if ! ${SHELL} -c "${CMD}" 2>&1 | debug; then
+		if ! run_command "${CMD}"; then
 			rm -f "${PACKAGE_CONFIGURE}"
-			local ERR_MSG='Failed building configure.'
-			[ ${VERBOSE_LEVEL} -ge 4 ] || ERR_MSG+=" Rerun with '--verbose=4' to see details."
-			die "${ERR_MSG}"
+			die 'Failed building configure.'
 		fi
 	fi
 }
@@ -2475,27 +2506,6 @@ EOF
 }
 
 ################################################ build/clean ########################################################
-
-function run_command()
-{
-	local COMMAND="$1"
-	local STATUS=0
-	local TMP_FILE
-	if [ "${SILENT_BUILD}" = 'yes' ]; then
-		TMP_FILE="$(mktemp)"
-		"${SHELL}" -c "${COMMAND}" &> "${TMP_FILE}"
-		STATUS=$?
-		if [ ${STATUS} -ne 0 ]; then
-			tail -n 200 "${TMP_FILE}" >&2
-		fi
-		rm -f "${TMP_FILE}"
-	else
-		"${SHELL}" -c "${COMMAND}"
-		STATUS=$?
-	fi
-
-	return ${STATUS}
-}
 
 function do_build()
 {
@@ -2720,11 +2730,6 @@ function main()
 				;;
 			--synthesize)
 				SYNTHESIZE='yes'
-				shift
-				;;
-			--silent-build)
-				OPTIONS+=("$1")
-				SILENT_BUILD='yes'
 				shift
 				;;
 			--dont-run-build-command)
